import Link from "next/link";
import { Role } from "@/generated/prisma/client";
import { decidePartRequest, issuePart } from "@/app/inventory-actions";
import { ensureInvoice } from "@/app/billing-actions";
import { requireRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { date, money } from "@/lib/format";

export default async function Finance() {
  await requireRole([Role.FINANCE]);
  const [requests, invoices, uninvoicedJobs] = await Promise.all([
    db.partRequest.findMany({ where: { status: { in: ["REQUESTED", "APPROVED"] } }, include: { part: true, job: { include: { customer: true } } }, orderBy: { createdAt: "asc" } }),
    db.invoice.findMany({ include: { job: { include: { customer: true } }, items: true, payments: true }, orderBy: { createdAt: "desc" } }),
    db.job.findMany({ where: { status: "COMPLETED", invoice: null }, include: { customer: true }, orderBy: { closedAt: "desc" } }),
  ]);
  const due = invoices.filter(invoice => invoice.status !== "DRAFT").reduce((sum, invoice) => sum + invoice.items.reduce((s, item) => s + item.quantity*item.unitCents, 0) - invoice.payments.reduce((s,payment) => s+payment.amountCents, 0), 0);
  const received = invoices.reduce((sum, invoice) => sum + invoice.payments.reduce((s,payment) => s+payment.amountCents, 0), 0);
  return <main className="content"><div className="page-head"><div><h1>Finance</h1></div></div>
    <div className="grid three mb"><div className="card stat"><div className="label">Open part requests</div><div className="value">{requests.length}</div></div><div className="card stat"><div className="label">Outstanding balance</div><div className="value">{money(due)}</div></div><div className="card stat"><div className="label">Payments received</div><div className="value">{money(received)}</div></div></div>
    <section className="card mb"><div className="section-title"><h2>Part requests</h2><span className="pill">{requests.length} pending</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Part</th><th>Requested</th><th>Stock</th><th>Price</th><th>Note</th><th>Action</th></tr></thead><tbody>{requests.map(request => <tr key={request.id}><td><Link className="text-link" href={`/jobs/${request.jobId}`}>#{String(request.job.number).padStart(5,"0")}</Link><br/><small>{request.job.customer.name}</small></td><td>{request.part.name}<br/><small>{request.part.sku}</small></td><td>{request.requestedQty}</td><td>{request.part.stockQty}</td><td>{money(request.part.priceCents)}</td><td>{request.note || "—"}</td><td>{request.status === "REQUESTED" ? <div className="actions"><form action={decidePartRequest.bind(null, request.id)}><input type="hidden" name="decision" value="APPROVED"/><button className="btn btn-teal btn-small">Approve</button></form><form action={decidePartRequest.bind(null, request.id)}><input type="hidden" name="decision" value="REJECTED"/><button className="btn btn-danger btn-small">Reject</button></form></div> : <form action={issuePart.bind(null, request.id)} className="inline-form"><div style={{ width: 70 }}><label htmlFor={`qty-${request.id}`}>Issue qty</label><input id={`qty-${request.id}`} type="number" name="quantity" min="1" max={request.requestedQty} defaultValue={request.requestedQty} required/></div><button className="btn btn-primary btn-small">Issue</button></form>}</td></tr>)}</tbody></table>{!requests.length && <div className="empty">No part requests need action.</div>}</div></section>
    {!!uninvoicedJobs.length && <section className="card mb"><div className="section-title"><h2>Completed jobs awaiting invoice</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Customer</th><th>Completed</th><th></th></tr></thead><tbody>{uninvoicedJobs.map(job => <tr key={job.id}><td><Link className="text-link" href={`/jobs/${job.id}`}>#{String(job.number).padStart(5,"0")}</Link></td><td>{job.customer.name}</td><td>{date(job.closedAt)}</td><td><form action={ensureInvoice.bind(null, job.id)}><button className="btn btn-secondary btn-small">Prepare invoice</button></form></td></tr>)}</tbody></table></div></section>}
    <section className="card"><div className="section-title"><h2>Invoices</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Job</th><th>Customer</th><th>Total</th><th>Balance</th><th>Status</th><th>Created</th></tr></thead><tbody>{invoices.map(invoice => { const total = invoice.items.reduce((s,i)=>s+i.quantity*i.unitCents,0); const paid = invoice.payments.reduce((s,p)=>s+p.amountCents,0); return <tr key={invoice.id}><td><Link className="text-link" href={`/finance/invoices/${invoice.id}`}>INV-{String(invoice.number).padStart(5,"0")}</Link></td><td>#{String(invoice.job.number).padStart(5,"0")}</td><td>{invoice.job.customer.name}</td><td>{money(total)}</td><td>{money(total-paid)}</td><td><span className={`pill ${invoice.status.toLowerCase()}`}>{invoice.status.toLowerCase()}</span></td><td>{date(invoice.createdAt)}</td></tr>; })}</tbody></table>{!invoices.length && <div className="empty">Invoices will appear when parts or labor are added.</div>}</div></section>
  </main>;
}
