import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const storageRoot = process.env.DIAGNOSTIC_STORAGE_PATH || join(process.cwd(), "storage");

function filePath(key: string) {
  // Keys are generated by the upload route. Reject unexpected database values too.
  const isValid =
    /^diagnostics\/[a-zA-Z0-9_-]+\/[0-9a-f-]{36}\.(pdf|jpg)$/i.test(key) ||
    /^vehicles\/[a-zA-Z0-9_-]+\/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$/i.test(key);
  if (!isValid) throw new Error("Invalid storage file key.");
  return join(/*turbopackIgnore: true*/ storageRoot, ...key.split("/"));
}

export async function putPrivateObject(key: string, bytes: Uint8Array) {
  const path = filePath(key);
  await mkdir(join(/*turbopackIgnore: true*/ storageRoot, ...key.split("/").slice(0, -1)), { recursive: true, mode: 0o700 });
  await writeFile(path, bytes, { flag: "wx", mode: 0o600 });
}

export async function getPrivateObject(key: string) {
  try {
    return await readFile(filePath(key));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}
