import Link from "next/link";
import { notFound } from "next/navigation";
import { Role } from "@/generated/prisma/client";
import { updateCustomer, updateVehicle } from "@/app/customer-actions";
import { requireRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { date } from "@/lib/format";

export default async function CustomerDetail({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireRole([Role.SUPERVISOR, Role.FINANCE]);
  const { id } = await params;
  const customer = await db.customer.findUnique({ where: { id }, include: { vehicles: { include: { model: true }, orderBy: { createdAt: "desc" } }, jobs: { orderBy: { createdAt: "desc" }, take: 20 } } });
  if (!customer) notFound();
  const edit = user.role === Role.SUPERVISOR || user.role === Role.ADMIN;
  const models = edit ? await db.vehicleModel.findMany({ orderBy: { name: "asc" } }) : [];
  return <main className="content"><div className="page-head"><div><div className="eyebrow">Customers</div><h1>{customer.name}</h1><p className="subtitle">{customer.phone} · {customer.vehicles.length} vehicles</p></div><Link className="btn btn-secondary" href="/customers">All customers</Link></div>
    <div className="grid two mb"><section className="card"><h2>Customer details</h2>{edit ? <form action={updateCustomer.bind(null,id)} className="stack"><div><label htmlFor="name">Name</label><input id="name" name="name" defaultValue={customer.name} required/></div><div><label htmlFor="phone">Phone</label><input id="phone" name="phone" defaultValue={customer.phone} required/></div><div><label htmlFor="email">Email</label><input id="email" name="email" type="email" defaultValue={customer.email || ""}/></div><div><label htmlFor="notes">Notes</label><textarea id="notes" name="notes" defaultValue={customer.notes || ""}/></div><button className="btn btn-primary" style={{ alignSelf: "start" }}>Save customer</button></form> : <dl className="detail-list"><dt>Phone</dt><dd>{customer.phone}</dd><dt>Email</dt><dd>{customer.email || "—"}</dd><dt>Notes</dt><dd>{customer.notes || "—"}</dd></dl>}</section><section className="card"><h2>Recent jobs</h2><div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Opened</th><th>Status</th></tr></thead><tbody>{customer.jobs.map(job => <tr key={job.id}><td><Link className="text-link" href={`/jobs/${job.id}`}>#{String(job.number).padStart(5,"0")}</Link></td><td>{date(job.createdAt)}</td><td><span className={`pill ${job.status.toLowerCase()}`}>{job.status.replaceAll("_"," ").toLowerCase()}</span></td></tr>)}</tbody></table>{!customer.jobs.length && <div className="empty">No jobs.</div>}</div></section></div>
    <section className="card"><h2>Vehicles</h2><div className="grid two">{customer.vehicles.map(vehicle => <div className="card" key={vehicle.id}><h3>{vehicle.year} Mercedes-Benz {vehicle.model?.name || vehicle.customModel}</h3>{edit ? <form action={updateVehicle.bind(null,vehicle.id)} className="stack"><div className="form-grid"><div><label htmlFor={`year-${vehicle.id}`}>Year</label><input id={`year-${vehicle.id}`} name="year" type="number" min="1926" max={new Date().getFullYear()+1} defaultValue={vehicle.year} required/></div><div><label htmlFor={`model-${vehicle.id}`}>Model</label><input id={`model-${vehicle.id}`} name="modelName" list="customer-mercedes-models" defaultValue={vehicle.model?.name || vehicle.customModel || ""} required/></div><div><label htmlFor={`vin-${vehicle.id}`}>VIN</label><input id={`vin-${vehicle.id}`} name="vin" maxLength={17} defaultValue={vehicle.vin || ""}/></div><div><label htmlFor={`plate-${vehicle.id}`}>Plate</label><input id={`plate-${vehicle.id}`} name="plate" defaultValue={vehicle.plate || ""}/></div><div><label htmlFor={`color-${vehicle.id}`}>Color</label><input id={`color-${vehicle.id}`} name="color" defaultValue={vehicle.color || ""}/></div></div><button className="btn btn-secondary" style={{ alignSelf: "start" }}>Save vehicle</button></form> : <dl className="detail-list"><dt>VIN</dt><dd>{vehicle.vin || "—"}</dd><dt>Plate</dt><dd>{vehicle.plate || "—"}</dd></dl>}</div>)}{!customer.vehicles.length && <div className="empty">No vehicles recorded.</div>}</div>{edit && <datalist id="customer-mercedes-models">{models.map(model => <option value={model.name} key={model.id}/>)}</datalist>}</section>
  </main>;
}
