import Link from "next/link";
import { notFound } from "next/navigation";
import { FileText, Plus, CheckCircle2 } from "lucide-react";
import { Role } from "@/generated/prisma/client";
import { canViewJob } from "@/lib/auth";
import { db } from "@/lib/db";
import { date, money } from "@/lib/format";
import { assignTechnician, closeJob, requestPart, updateChecklist, updateFindings } from "@/app/job-actions";

export default async function JobDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await canViewJob(id);
  const job = await db.job.findUnique({ where: { id }, include: {
    customer: true, vehicle: { include: { model: true } }, technician: true,
    checklist: { orderBy: { sortOrder: "asc" } }, diagnostics: { orderBy: { createdAt: "desc" }, include: { uploadedBy: true } },
    partRequests: { include: { part: true }, orderBy: { createdAt: "desc" } },
    invoice: { include: { items: true, payments: true } },
  } });
  if (!job) notFound();
  const edit = (user.role === Role.SUPERVISOR || user.role === Role.ADMIN) && job.status !== "COMPLETED";
  const [technicians, parts] = await Promise.all([
    edit ? db.user.findMany({ where: { role: Role.TECHNICIAN, active: true }, orderBy: { name: "asc" } }) : Promise.resolve([]),
    edit ? db.part.findMany({ where: { active: true }, orderBy: { name: "asc" } }) : Promise.resolve([]),
  ]);
  const total = job.invoice?.items.reduce((sum, item) => sum + item.quantity * item.unitCents, 0) || 0;
  const paid = job.invoice?.payments.reduce((sum, payment) => sum + payment.amountCents, 0) || 0;
  return <main className="content">
    <div className="page-head"><div><div className="eyebrow">Workshop / Job orders</div><h1>Job #{String(job.number).padStart(5,"0")}</h1><p className="subtitle">Opened {date(job.createdAt)} · {job.customer.name}</p></div><div className="row wrap"><span className={`pill ${job.status.toLowerCase()}`}>{job.status.replaceAll("_"," ").toLowerCase()}</span><Link className="btn btn-secondary" href="/jobs">All jobs</Link></div></div>
    <div className="grid two mb"><section className="card"><div className="section-title"><h2>Customer & vehicle</h2></div><dl className="detail-list"><dt>Customer</dt><dd>{job.customer.name}</dd><dt>Phone</dt><dd>{job.customer.phone}</dd><dt>Email</dt><dd>{job.customer.email || "—"}</dd><dt>Vehicle</dt><dd>{job.vehicle.year} Mercedes-Benz {job.vehicle.model?.name || job.vehicle.customModel}</dd><dt>VIN</dt><dd>{job.vehicle.vin || "—"}</dd><dt>Plate</dt><dd>{job.vehicle.plate || "—"}</dd><dt>Mileage</dt><dd>{job.vehicle.mileage?.toLocaleString() || "—"}</dd></dl></section>
      <section className="card"><div className="section-title"><h2>Job details</h2></div><p className="muted" style={{ fontSize: ".75rem", textTransform: "uppercase", fontWeight: 800 }}>Customer complaint</p><p style={{ whiteSpace: "pre-wrap" }}>{job.complaint}</p><div className="divider"/><dl className="detail-list"><dt>Technician</dt><dd>{job.technician?.name || "Unassigned"}</dd><dt>Closed</dt><dd>{date(job.closedAt)}</dd></dl>{edit && <form action={assignTechnician.bind(null, id)} className="inline-form mt"><div style={{ flex: 1 }}><label htmlFor="technicianId">Assign technician</label><select id="technicianId" name="technicianId" defaultValue={job.technicianId || ""}><option value="">Unassigned</option>{technicians.map(tech => <option key={tech.id} value={tech.id}>{tech.name}</option>)}</select></div><button className="btn btn-secondary">Save</button></form>}</section></div>
    <div className="grid two mb"><section className="card"><div className="section-title"><h2>Inspection checklist</h2><span className="pill">{job.checklist.filter(item => item.result).length}/{job.checklist.length} checked</span></div>{job.checklist.length ? job.checklist.map(item => <div className="check-row" key={item.id}><strong>{item.label}</strong>{edit ? <form action={updateChecklist.bind(null, item.id)} style={{ display: "contents" }}><select name="result" defaultValue={item.result || ""} aria-label={`${item.label} result`}><option value="">Not checked</option><option value="PASS">Pass</option><option value="ATTENTION">Needs attention</option><option value="NOT_APPLICABLE">N/A</option></select><input name="note" defaultValue={item.note || ""} placeholder="Note (optional)" aria-label={`${item.label} note`}/><button className="btn btn-secondary btn-small">Save</button></form> : <><span className={`pill ${item.result === "ATTENTION" ? "rejected" : item.result === "PASS" ? "paid" : ""}`}>{item.result?.replaceAll("_", " ") || "Not checked"}</span><span className="muted">{item.note || ""}</span></>}</div>) : <div className="empty">No checklist was selected for this job.</div>}</section>
      <section className="card"><div className="section-title"><h2>Diagnostics & findings</h2></div>{edit ? <form action={updateFindings.bind(null, id)} className="stack"><div><label htmlFor="findings">Supervisor findings</label><textarea id="findings" name="findings" defaultValue={job.findings || ""} placeholder="Record inspection and diagnostic findings"/></div><button className="btn btn-secondary" style={{ alignSelf: "start" }}>Save findings</button></form> : <p style={{ whiteSpace: "pre-wrap" }}>{job.findings || "No findings recorded yet."}</p>}<div className="divider"/><h3>Diagnostic files</h3><div className="stack">{job.diagnostics.map(file => <a className="text-link row" href={`/api/diagnostics/${file.id}`} key={file.id}><FileText size={16}/>{file.name} <small>· {date(file.createdAt)}</small></a>)}{!job.diagnostics.length && <span className="muted">No files uploaded yet.</span>}</div>{edit && <form action={`/api/jobs/${id}/diagnostics`} method="post" encType="multipart/form-data" className="stack mt"><div><label htmlFor="diagnostic">Upload initial diagnostic (PDF or JPG, max 10 MB)</label><input id="diagnostic" name="file" type="file" accept=".pdf,.jpg,.jpeg,application/pdf,image/jpeg" required/></div><button className="btn btn-secondary" style={{ alignSelf: "start" }}>Upload file</button></form>}</section></div>
    <section className="card mb"><div className="section-title"><h2>Parts requests</h2><span className="pill">{job.partRequests.length} requests</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Part</th><th>SKU</th><th>Requested</th><th>Issued</th><th>Price</th><th>Status</th><th>Note</th></tr></thead><tbody>{job.partRequests.map(request => <tr key={request.id}><td>{request.part.name}</td><td>{request.part.sku}</td><td>{request.requestedQty}</td><td>{request.issuedQty}</td><td>{money(request.part.priceCents)}</td><td><span className={`pill ${request.status.toLowerCase()}`}>{request.status.toLowerCase()}</span></td><td>{request.note || request.decisionNote || "—"}</td></tr>)}</tbody></table>{!job.partRequests.length && <div className="empty">No parts requested.</div>}</div>{edit && <><div className="divider"/><form action={requestPart.bind(null, id)} className="form-grid"><div className="field"><label htmlFor="partId">Part</label><select id="partId" name="partId" required defaultValue=""><option value="" disabled>Select part</option>{parts.map(part => <option value={part.id} key={part.id}>{part.name} · {part.sku} · {money(part.priceCents)} ({part.stockQty} in stock)</option>)}</select></div><div className="field"><label htmlFor="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="1" step="1" defaultValue="1" required/></div><div className="field field-wide"><label htmlFor="requestNote">Request note</label><input id="requestNote" name="note" placeholder="Why this part is needed"/></div><div><button className="btn btn-primary"><Plus size={16}/> Request part</button></div></form></>}</section>
    <section className="card"><div className="section-title"><h2>Invoice</h2>{job.invoice && (user.role === Role.ADMIN || user.role === Role.FINANCE) && <Link className="btn btn-secondary btn-small" href={`/finance/invoices/${job.invoice.id}`}>View invoice</Link>}</div>{job.invoice ? <div className="grid three"><div><small>Total</small><h2>{money(total)}</h2></div><div><small>Paid</small><h2>{money(paid)}</h2></div><div><small>Balance</small><h2>{money(total-paid)}</h2></div></div> : <p className="muted">Finance will prepare the invoice when parts or labor are added.</p>}</section>
    {edit && <form action={closeJob.bind(null, id)} className="mt" style={{ textAlign: "right" }}><button className="btn btn-teal"><CheckCircle2 size={16}/> Mark job complete</button><p className="hint">Resolve any pending parts requests before closing.</p></form>}
  </main>;
}
