import Link from "next/link";
import { notFound } from "next/navigation";
import { Role } from "@/generated/prisma/client";
import { addLabor, issueInvoice, recordPayment, removeLabor } from "@/app/billing-actions";
import { requireRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { date, money } from "@/lib/format";

export default async function InvoiceDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireRole([Role.FINANCE]);
  const { id } = await params;
  const invoice = await db.invoice.findUnique({ where: { id }, include: { job: { include: { customer: true, vehicle: { include: { model: true } } } }, items: { orderBy: { createdAt: "asc" } }, payments: { orderBy: { paidAt: "desc" } } } });
  if (!invoice) notFound();
  const total = invoice.items.reduce((sum,item)=>sum+item.quantity*item.unitCents,0);
  const paid = invoice.payments.reduce((sum,payment)=>sum+payment.amountCents,0);
  const balance = total-paid;
  return <main className="content"><div className="page-head"><div><div className="eyebrow">Finance / Invoices</div><h1>Invoice INV-{String(invoice.number).padStart(5,"0")}</h1><p className="subtitle">For job #{String(invoice.job.number).padStart(5,"0")} · {invoice.job.customer.name}</p></div><div className="row"><span className={`pill ${invoice.status.toLowerCase()}`}>{invoice.status.toLowerCase()}</span><Link className="btn btn-secondary" href="/finance">Finance desk</Link></div></div>
    <div className="grid three mb"><div className="card stat"><div className="label">Invoice total</div><div className="value">{money(total)}</div></div><div className="card stat"><div className="label">Payments</div><div className="value">{money(paid)}</div></div><div className="card stat"><div className="label">Balance due</div><div className="value">{money(balance)}</div></div></div>
    <section className="card mb"><div className="section-title"><h2>Line items</h2><small>{invoice.job.vehicle.year} {invoice.job.vehicle.model?.name || invoice.job.vehicle.customModel}</small></div><div className="table-wrap"><table className="table"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Unit</th><th>Total</th><th></th></tr></thead><tbody>{invoice.items.map(item => <tr key={item.id}><td><span className="pill">{item.type.toLowerCase()}</span></td><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unitCents)}</td><td>{money(item.quantity*item.unitCents)}</td><td>{invoice.status === "DRAFT" && item.type === "LABOR" && <form action={removeLabor.bind(null, item.id)}><button className="btn btn-danger btn-small">Remove</button></form>}</td></tr>)}</tbody></table>{!invoice.items.length && <div className="empty">Add labor or issue a requested part to create invoice lines.</div>}</div></section>
    {invoice.status === "DRAFT" && <div className="grid two mb"><section className="card"><h2>Add labor or service</h2><form action={addLabor.bind(null,id)} className="stack"><div><label htmlFor="description">Description</label><input id="description" name="description" required maxLength={250} placeholder="Diagnostic labor, fitting, servicing..."/></div><div className="form-grid"><div><label htmlFor="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="1" step="1" defaultValue="1" required/></div><div><label htmlFor="price">Unit price</label><input id="price" name="price" type="number" min="0" step="0.01" required/></div></div><button className="btn btn-primary" style={{ alignSelf: "start" }}>Add charge</button></form></section><section className="card"><h2>Issue invoice</h2><p className="subtitle mb">The supervisor must close the job first. Once issued, invoice lines are fixed and payments can be recorded.</p><dl className="detail-list"><dt>Job status</dt><dd>{invoice.job.status.replaceAll("_", " ")}</dd><dt>Issued</dt><dd>{date(invoice.issuedAt)}</dd></dl><form action={issueInvoice.bind(null,id)} className="mt"><button className="btn btn-teal" disabled={invoice.job.status !== "COMPLETED" || !invoice.items.length}>Issue invoice</button></form></section></div>}
    <div className="grid two"><section className="card"><h2>Payments</h2><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{invoice.payments.map(payment => <tr key={payment.id}><td>{date(payment.paidAt)}</td><td>{payment.method}</td><td>{payment.reference || "—"}</td><td>{money(payment.amountCents)}</td></tr>)}</tbody></table>{!invoice.payments.length && <div className="empty">No payments recorded.</div>}</div></section>{invoice.status !== "DRAFT" && balance > 0 && <section className="card"><h2>Record payment</h2><form action={recordPayment.bind(null,id)} className="stack"><div><label htmlFor="amount">Amount</label><input id="amount" name="amount" type="number" min="0.01" max={(balance/100).toFixed(2)} step="0.01" required/></div><div><label htmlFor="method">Method</label><select id="method" name="method" required><option value="Cash">Cash</option><option value="Card">Card</option><option value="Bank transfer">Bank transfer</option><option value="Mobile money">Mobile money</option></select></div><div><label htmlFor="reference">Reference (optional)</label><input id="reference" name="reference" maxLength={100}/></div><button className="btn btn-primary" style={{ alignSelf: "start" }}>Record payment</button></form></section>}</div>
  </main>;
}
